Now i know

In [1]:
import pandas as pd
import numpy as np

In [2]:
test = pd.read_csv('test.csv')
train = pd.read_csv('train.csv')

test

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
27995       0       0       0       0       0       0       0       0       0   
27996       0       0       0       0       0       0       0       0       0   
27997       0       0       0       0       0       0       0       0       0   
27998       0       0       0       0       0       0       0       0       0   
27999       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
27995       0  ...         0         0         0         0         0   
27996       0  ...         0         0         0         0         0   
27997       0  ...         0         0         0         0         0   
27998       0  ...         0         0         0         0         0   
27999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
27995         0         0         0         0         0  
27996         0         0         0         0         0  
27997         0         0         0         0         0  
27998         0         0         0         0         0  
27999         0         0         0         0         0  

[28000 rows x 784 columns]

In [3]:
train

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [4]:
from tensorflow.keras.layers import Dense
from tensorflow.keras import Model,Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

model = Sequential(
    [
        Dense(64,activation='relu'),
        Dense(32,activation='relu'),
        Dense(10,activation='softmax')
    ]
)
optimizer = Adam(learning_rate=0.001)

2022-10-06 19:21:15.371493: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-06 19:21:15.519630: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-06 19:21:15.519645: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-10-06 19:21:15.553193: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-06 19:21:16.190325: W tensorflow/stream_executor/platform/de

Feature engineering y_train to be probabilistic prediction of number.

And dividing train to val and train set.

I need to make this feature engineerings as functions and i will def them when i go home byee.

For example: 1 -> [0,1,0,0,0,0,0,0,0,0]

In [16]:
x_train = np.array(train.iloc[:30000,1:])
y_train = np.array(train.iloc[:30000,0])
val_train = np.array(train.iloc[30000:,1:])
val_test = np.array(train.iloc[30000:,1:])
x_test = np.array(test.iloc[:,:])
prob_y_train = np.zeros((len(y_train),10))
for i in range(len(y_train)):
    num = y_train[i]
    prob_y_train[i][num] = 1
for x in range(5):
    print(prob_y_train[x],y_train[x])

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] 4
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0


In [17]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy
loss = SparseCategoricalCrossentropy(from_logits=True)

In [18]:
model.compile(optimizer,loss)

In [19]:
model.fit(x_train,y_train, epochs=10)

Epoch 1/10
938/938 [==============================] - 1s 845us/step - loss: 0.0406
Epoch 2/10
938/938 [==============================] - 1s 843us/step - loss: 0.0405
Epoch 3/10
938/938 [==============================] - 1s 865us/step - loss: 0.0398
Epoch 4/10
938/938 [==============================] - 1s 968us/step - loss: 0.0495
Epoch 5/10
938/938 [==============================] - 1s 862us/step - loss: 0.0477
Epoch 6/10
938/938 [==============================] - 1s 850us/step - loss: 0.0407
Epoch 7/10
938/938 [==============================] - 1s 853us/step - loss: 0.0450
Epoch 8/10
938/938 [==============================] - 1s 957us/step - loss: 0.0283
Epoch 9/10
938/938 [==============================] - 1s 937us/step - loss: 0.0329
Epoch 10/10
938/938 [==============================] - 1s 851us/step - loss: 0.0428


In [20]:
model(x_train)[3]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.0000000e+00, 7.3034536e-20, 2.9511839e-23, 2.2210944e-38,
       9.9999994e-01, 1.1960597e-20, 2.1339425e-14, 1.8125449e-27,
       0.0000000e+00, 4.8294927e-11], dtype=float32)>