Now i know

In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
test = pd.read_csv('test.csv')
train = pd.read_csv('train.csv')

test

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
27995       0       0       0       0       0       0       0       0       0   
27996       0       0       0       0       0       0       0       0       0   
27997       0       0       0       0       0       0       0       0       0   
27998       0       0       0       0       0       0       0       0       0   
27999       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
27995       0  ...         0         0         0         0         0   
27996       0  ...         0         0         0         0         0   
27997       0  ...         0         0         0         0         0   
27998       0  ...         0         0         0         0         0   
27999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
27995         0         0         0         0         0  
27996         0         0         0         0         0  
27997         0         0         0         0         0  
27998         0         0         0         0         0  
27999         0         0         0         0         0  

[28000 rows x 784 columns]

In [3]:
train

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [4]:
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
from tensorflow.keras.layers import Dense
from tensorflow.keras import Model, Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

model = Sequential(
    [Dense(64, activation='relu'),
     Dense(32, activation='relu'),
     Dense(10)])
optimizer = Adam(learning_rate=0.001)

Function for dividing to validation and train 

And changing y_train to be probabilistic prediction of number.

For example: 1 -> [0,1,0,0,0,0,0,0,0,0]

In [5]:
def divide_to_val_and_train(df, percentage):
    length = len(df)
    train_len = math.floor(length / 5 * 4)
    x_train = np.array(df.iloc[:train_len, 1:])
    y_train = np.array(df.iloc[:train_len, 0])
    x_val = np.array(df.iloc[train_len:, 1:])
    y_val = np.array(df.iloc[train_len:, 0])

    return x_train, y_train, x_val, y_val

def y_to_prob(y, label_len=10):
    prob_y = np.zeros((len(y), label_len))
    for i in range(len(y)):
        num = y[i]
        prob_y[i][num] = 1
    return prob_y

def prob_to_y(y, label_len=10):
    real_y = np.zeros((len(y), ))
    for i in range(len(y)):
        for j in range(label_len):
            if y[i][j]==1:
                real_y[i] = j
    return real_y
            
def printarr(arr, length=10):
    for i in range(length):
        print(arr[i])

In [6]:
x_test = np.array(test.iloc[:, :])
x_train, y_train, x_val, y_val = divide_to_val_and_train(df=train,
                                                              percentage=0.8)
y_train = y_to_prob(y_train)
y_val = y_to_prob(y_val)
printarr(y_train)

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [7]:
from tensorflow.keras.losses import CategoricalCrossentropy
loss = CategoricalCrossentropy(from_logits=True)

In [8]:
model.compile(optimizer,loss)

In [9]:
model.fit(x_train,y_train, epochs=10)

Epoch 1/10
1050/1050 [==============================] - 1s 1ms/step - loss: 2.0928
Epoch 2/10
1050/1050 [==============================] - 1s 1ms/step - loss: 0.7150
Epoch 3/10
1050/1050 [==============================] - 1s 991us/step - loss: 0.5559
Epoch 4/10
1050/1050 [==============================] - 1s 988us/step - loss: 0.4321
Epoch 5/10
1050/1050 [==============================] - 1s 809us/step - loss: 0.3319
Epoch 6/10
1050/1050 [==============================] - 1s 820us/step - loss: 0.2640
Epoch 7/10
1050/1050 [==============================] - 1s 1ms/step - loss: 0.2287
Epoch 8/10
1050/1050 [==============================] - 1s 940us/step - loss: 0.1970
Epoch 9/10
1050/1050 [==============================] - 1s 1ms/step - loss: 0.1810
Epoch 10/10
1050/1050 [==============================] - 1s 837us/step - loss: 0.1559


In [10]:
from tensorflow.keras.activations import softmax
pred_train = model(x_train)
pred_train = softmax(pred_train)
pred_train = np.round(pred_train)

pred_val = model(x_val)
pred_val = softmax(pred_val)
pred_val = np.round(pred_val)

In [11]:
def compare_results(pred,y):
    same_results = 0
    for i in range(len(y)):
        same_results += np.array_equal(y[i],pred[i])#y[i][:]==pred[i][:] np 
    same_results = same_results/len(y)
    return same_results
    

In [12]:
val_acc = compare_results(pred_val,y_val)
print(val_acc)
train_acc = compare_results(pred_train,y_train)
print(train_acc)

0.9365476190476191
0.9564880952380952


Here i will try to show the ones i predict wrong

In [21]:
def get_wrong_results_index(pred,y,x):
    wrong_results = []
    for i in range(len(y)):
        if np.array_equal(y[i],pred[i]) == 0:
            wrong_results.append(i)
    return wrong_results


In [22]:
wrong_results = get_wrong_results(pred_val,y_val,x_val)

In [ ]:
wrong_results

In [19]:
pr

[0. 7. 7. ... 7. 6. 9.]
